# Generated by Django 5.2.7 on 2025-12-27 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='architect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=1000)),
                ('dist', models.CharField(max_length=100)),
                ('post_office', models.CharField(max_length=1000)),
                ('certificate', models.FileField(upload_to='')),
                ('pin_no', models.BigIntegerField()),
                ('stat', models.CharField(default='Pending', max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chatss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('fro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mobile_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=1000)),
                ('dist', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='complai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complai', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('MOBILE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mobile_user')),
            ],
        ),
        migrations.CreateModel(
            name='work_design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('ARCHITECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.architect')),
            ],
        ),
        migrations.CreateModel(
            name='work_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('requ', models.CharField(max_length=100)),
                ('stat', models.CharField(default='Pending', max_length=100)),
                ('MOBILE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mobile_user')),
                ('WORK_DESIGN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.work_design')),
            ],
        ),
    ]
